apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Selmouni-Abdelilah/api_gitops.git
      targetRevision: HEAD
      path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

